### ISSUE TITLE
Converting a dxf file to gcode using DXF2GCODE

### ISSUE THREAD

**Issue by Omegaduc** [vzzederzv/SE04-Nhom22.1#1]
dxf file: http://www.cnccookbook.com/dxf-downloads/knot_004.DXF

**Comment by Omegaduc** [comment]
Done
Simulated Gcode:
![Screenshot 2020-11-03 204342](https://user-images.githubusercontent.com/51270223/97992825-d1ec4180-1e15-11eb-9e22-793c92b45a73.png)

**Comment by doanhjut** [comment]
https://store.gardos-software.com/en/product/cnc-apps

**Comment by doanhjut** [comment]
https://cnc-apps.com/en/app/dxf2gcode

**Comment by doanhjut** [comment]
![Untitled-1](https://user-images.githubusercontent.com/68116621/103453776-009c7080-4d10-11eb-812e-567fd09fbb27.png)
