### ISSUE TITLE
Tìm hiểu và sử dụng AlphaCAM Ultimate Router

### ISSUE THREAD

**Issue by vzzederzv** [vzzederzv/SE04-Nhom22.1#9]

**Comment by endeeayy** [comment]
update hướng dẫn sử dụng vào

**Comment by Omegaduc** [comment]
File dxf: https://github.com/vzzederzv/SE04-Nhom22.1/blob/main/00154973_18mmw2440_h1220_1_Z.dxf

**Comment by Omegaduc** [comment]
### **Import file DXF vào Alphacam:**
1. Chức năng Input CAD.
![image](https://user-images.githubusercontent.com/51270223/103476464-960b3380-4de8-11eb-8d92-6d604d28de33.png)

2. Chọn định dạng DXF.
![image](https://user-images.githubusercontent.com/51270223/103476484-c357e180-4de8-11eb-97ef-51c382a82b5f.png)

3. Chọn file DXF.
![image](https://user-images.githubusercontent.com/51270223/103476488-d4085780-4de8-11eb-9b5b-e61e6d95c4a8.png)

4. File DXF mẫu.
![image](https://user-images.githubusercontent.com/51270223/103476494-dff41980-4de8-11eb-9780-ae28faad6888.png)

**Comment by Omegaduc** [comment]
### **Cài đặt các thông số của vật liệu:**

1. Chức năng Set Material.
![image](https://user-images.githubusercontent.com/51270223/103476519-3c573900-4de9-11eb-85e3-09e42caaa2fa.png)

2. Nhập vào thông số vật liệu.
![image](https://user-images.githubusercontent.com/51270223/103476531-5264f980-4de9-11eb-8fb1-7541d6e29bb0.png)

3. Chức năng Set Geometry Z Levels.
![image](https://user-images.githubusercontent.com/51270223/103476536-60b31580-4de9-11eb-96dc-eb9d024233bc.png)

4. Tạo độ sâu của từng nét cắt theo yêu cầu.
![image](https://user-images.githubusercontent.com/51270223/103476544-732d4f00-4de9-11eb-8795-8f853f2711a1.png)

**Comment by Omegaduc** [comment]
### **Chọn công cụ gia công và thao tác thi công:**

1. Bảng chọn công cụ gia công.
![image](https://user-images.githubusercontent.com/51270223/103476601-ea62e300-4de9-11eb-800b-713f92abb2dc.png)

2. Chức năng Pocket Holes.
![image](https://user-images.githubusercontent.com/51270223/103476610-0070a380-4dea-11eb-9ae5-9458570382ad.png)

3. Thiết lập thông số của lỗ cần đục.
![image](https://user-images.githubusercontent.com/51270223/103476618-0ebebf80-4dea-11eb-8027-8cca69edf9ea.png)

4. Chọn lỗ để đục.
![image](https://user-images.githubusercontent.com/51270223/103476624-1e3e0880-4dea-11eb-90c8-1535126f163a.png)

5. Hành trình của mũi khoan.
![image](https://user-images.githubusercontent.com/51270223/103476637-33b33280-4dea-11eb-9b7c-35f2001758ac.png)

6. Thiết lập thông số của đường cắt.
![image](https://user-images.githubusercontent.com/51270223/103476641-43327b80-4dea-11eb-84cb-4a5c4b4b5463.png)

7. Chọn phần muốn cắt.
![image](https://user-images.githubusercontent.com/51270223/103476650-51809780-4dea-11eb-9149-a85488ea88b8.png)

8. Hành trình của máy cắt.
![image](https://user-images.githubusercontent.com/51270223/103476660-62310d80-4dea-11eb-8265-b0b3f2f24419.png)

9. Toàn bộ hành trình của các công cụ gia công.
![image](https://user-images.githubusercontent.com/51270223/103476671-6eb56600-4dea-11eb-83db-9a5893bcad64.png)

**Comment by Omegaduc** [comment]
### **Chạy thử giả lập:**

1. Chức năng Send to Stimulator.
![image](https://user-images.githubusercontent.com/51270223/103476700-a7553f80-4dea-11eb-92b3-8f7d23258225.png)

2. Chế độ Giả lập.
![image](https://user-images.githubusercontent.com/51270223/103476713-bb993c80-4dea-11eb-8116-360336ed99eb.png)

3. Kết quả giả lập thi công.
![image](https://user-images.githubusercontent.com/51270223/103476719-c9e75880-4dea-11eb-99dd-4dce5e64b9d2.png)

**Comment by Omegaduc** [comment]
### **Xuất file G-Code:**

1. Chức năng Output NC.
![image](https://user-images.githubusercontent.com/51270223/103476769-26e30e80-4deb-11eb-985a-021071d2028d.png)

2. Chọn xuất ra File.
![image](https://user-images.githubusercontent.com/51270223/103476782-36faee00-4deb-11eb-9bc0-3f425d4e8912.png)

3. Lưu file G-Code.
![image](https://user-images.githubusercontent.com/51270223/103476791-49752780-4deb-11eb-92ff-c049de568160.png)

Link anc: https://github.com/vzzederzv/SE04-Nhom22.1/blob/main/test2.anc
